"""Quantum Performance Record (QPR): models, canonicalization, sealing, verification."""

from ._generated import (
    Benchmark,
    Circuit,
    Device,
    Execution,
    Integrity,
    Metric,
    MetricStatistics,
    Provenance,
    Provider,
    QuantumPerformanceRecord,
    RawResult,
    Results,
    Signature,
    Transpilation,
)
from .canonical import canonical_json, content_sha256, sha256_hex
from .records import (
    QPR_VERSION,
    SUPPORTED_QPR_MAJOR_VERSIONS,
    UnsupportedQprVersionError,
    dump_qpr,
    dumps_qpr,
    load_qpr,
    loads_qpr,
    qpr_major_version,
    seal,
    to_json_dict,
)
from .sign import (
    SigningUnavailableError,
    generate_signing_key,
    sign_qpr,
    signing_available,
    verify_signature,
)
from .verify import Issue, VerificationReport, verify_qpr_document, verify_qpr_file

__all__ = [
    "QPR_VERSION",
    "SUPPORTED_QPR_MAJOR_VERSIONS",
    "Benchmark",
    "Circuit",
    "Device",
    "Execution",
    "Integrity",
    "Issue",
    "Metric",
    "MetricStatistics",
    "Provenance",
    "Provider",
    "QuantumPerformanceRecord",
    "RawResult",
    "Results",
    "Signature",
    "SigningUnavailableError",
    "Transpilation",
    "UnsupportedQprVersionError",
    "VerificationReport",
    "canonical_json",
    "content_sha256",
    "dump_qpr",
    "dumps_qpr",
    "generate_signing_key",
    "load_qpr",
    "loads_qpr",
    "qpr_major_version",
    "seal",
    "sha256_hex",
    "sign_qpr",
    "signing_available",
    "to_json_dict",
    "verify_qpr_document",
    "verify_qpr_file",
    "verify_signature",
]
